openapi: '3.0.0'
info:
  version: 1.0.0
  title: Jackson Bravo API
  license:
    name: MIT
servers:
  - url: https://api.jacksonbravo.com/v1
paths:
  /designs:
    get:
      summary: List all designs
      operationId: listDesigns
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of designs
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Designs'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a design
      operationId: createDesigns
      responses:
        201:
          description: Design created successfully
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /designs/{designId}:
    get:
      summary: Info for a specific design
      operationId: showDesignById
      parameters:
        - name: designId
          in: path
          required: true
          description: The id of the design to retrieve
          schema:
            type: string
      responses:
        200:
          description: Design information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Designs'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Design:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Designs:
      type: array
      items:
        $ref: '#/components/schemas/Design'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
